[project]
name = "test"
description = "test"
requires-python = ">=3.11"

dependencies = [
    "Django==4.2.10",
    "ruff==0.3.1",
    "black==24.1.0",
]

[project.optional-dependencies]
tests = [
    "pytest==8.1.1"
]
